language: java
os: linux
dist: trusty
jdk: oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
addons:
  ssh_known_hosts:
    - 59.110.220.167
install:
  - ./gradlew build
script:
  - scp build/libs/* root@59.110.220.167:/home/work/justneo/
  - ssh root@59.110.220.167 "./deploy.ssh"
